### ISSUE TITLE
Bidirectional Serialised Data-Format for Graph

### ISSUE THREAD

**Issue by sordina** [visual-systems/philosophy#19]
Read and write serialised format for graph. Possibly in Dhall.

Represent the graph in a serialised format.

* Expose Types
* Expose Structure
* Expose Default/Test Implementations
* Expose Decorations for Nodes, Edges, Processes, and Subgraphs
* Expose Shared data-types

Potential Example:

```
---
    types:
        number: Integer
    nodes:
        x: number
        y: number
    processes:
        add:
            type: number -> number -> number
            implementation: (+)
    edges:
        - (x, add)
        - (y, add)
```
